### ISSUE TITLE
Dates in syslog logs are incorrect

### ISSUE THREAD

**Issue by elemoine** [salt-formulas/salt-formula-heka#11]
In the "stacklight" branch we use `generic_syslog.lua` from StackLight MOS as the syslog decoder instead of Heka's `rsyslog.lua`. The issue is that, contrary to `rsyslog.lua`, the `generic_syslog.lua` decoder does not accept a `tz` config option and actually does not work with non-UTC timezones. The consequence of this issue is logs displayed at incorrect dates (in the future) in Kibana.

This issue only applies to the "stacklight" branch.

**Comment by cznewt** [comment]
I think the linux formula handles syslog, I'll check. No, we will need to configure it to correct format.
the timezone can be set by parameter - it should be utc on all nodes?

**Comment by elemoine** [comment]
> I think the linux formula handles syslog

Yes.

> No, we will need to configure it to correct format.

I figured that what I am saying in the issue description is not correct. We should be able to reuse `generic_syslog.lua` as the `tz` config option is actually used from the Heka Go code.

> it should be utc on all nodes?

It should be set to the timezone used on the machine (Europe/Prague right now on our lab environment).

**Comment by elemoine** [comment]
https://github.com/tcpcloud/salt-formula-linux/pull/16 should fix it.

**Comment by elemoine** [comment]
Closing this. We decided not to create Issues for things specific to the stacklight branch.
