### ISSUE TITLE
Incorrect version of the Heka package is installed

### ISSUE THREAD

**Issue by simonpasquier** [salt-formulas/salt-formula-heka#14]
0.10.0 should be installed while it's 0.10.0b2.

```
# apt-cache policy heka
heka:
  Installed: 0.10.0b2
  Candidate: 0.10.0b2
  Version table:
 *** 0.10.0b2 0
        500 http://apt.tcpcloud.eu/nightly/ trusty/tcp amd64 Packages
        100 /var/lib/dpkg/status
     0.10.0b1 0
        500 http://apt.tcpcloud.eu/nightly/ trusty/tcp amd64 Packages
     0.10.0 0
        500 http://apt.tcpcloud.eu/nightly/ trusty/tcp amd64 Packages
```

See https://github.com/mozilla-services/heka/issues/1892 for the details. Either 0.10.0b1/0.10.0b2 versions should be removed from the apt repositories or the formula should pin the correct version.

**Comment by fpytloun** [comment]
Removed beta versions from our repository.

**Comment by elemoine** [comment]
Thanks for taking care of that @fpytloun.
